# Generated by Django 3.2.5 on 2021-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('プログラミング', 'プログラミング'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
