<<<<<<< HEAD
# Generated by Django 3.2.5 on 2022-03-19 13:46
=======
# Generated by Django 3.2.5 on 2021-09-23 14:55
>>>>>>> f9814dac0d3f401638c8a6fe9e9d719f64e15238

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('プログラミング', 'プログラミング'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
